"LR": 2.5e-4
"NUM_ENVS": 32
"NUM_STEPS": 256
"TOTAL_TIMESTEPS": 1e7
"UPDATE_EPOCHS": 4
"NUM_MINIBATCHES": 4
"GAMMA": 0.99
"GAE_LAMBDA": 0.95
"CLIP_EPS": 0.2
"ENT_COEF": 0.01
"VF_COEF": 0.5
"MAX_GRAD_NORM": 0.5
"REW_SHAPING_HORIZON": 2.5e6
"ACTIVATION": "tanh"
"ENV_NAME": "overcooked"
"ENV_KWARGS": 
  "random_reset" : False # relevant for which env to train/test on. If true, it is IK
  "max_steps": 256
  # toy specific kwargs
  "debug": False
  # overcooked specific kwargs
  "check_held_out": False  # if false, we don't check if the reset env is held out
  "shuffle_inv_and_pot": True # if true, we shuffle pot status and inventory
  "layout": "forced_coord_padded"
"ANNEAL_LR": True
"SEED": 30
"NUM_SEEDS": 2

# WandB Params
"ENTITY": "social-rl"                                          
"PROJECT": "InfiniteKitchen"
"WANDB_MODE" : "disabled"